### ISSUE TITLE
Transparent background is not working

### ISSUE THREAD

**Issue by f2404** [f2404/xfce4-terminal3#13]
The functionality has been removed from vte; need to remove from the preferences as well.
Same applies to the background image functionality.

**Comment by ochosi** [comment]
I think there might be ways to work around this, at least that is what is suggested here https://bugzilla.xfce.org/show_bug.cgi?id=11207#c19

For the background images see https://bugzilla.xfce.org/show_bug.cgi?id=11207#c30

**Comment by f2404** [comment]
Thanks, I've already started the transparency implementation based on using alpha channel. It's not stable enough yet.

**Comment by f2404** [comment]
Made it work in master - at least for Arch with GTK 3.20.
