### ISSUE TITLE
The terminal window is too small on start

### ISSUE THREAD

**Issue by f2404** [f2404/xfce4-terminal3#2]
Neither the terminal settings, nor the `--geometry` option are working.

**Comment by f2404** [comment]
Looks like the following code applies the geometry set in pixels rather than in columns and rows:

``` c
      /* try to apply the geometry to the window */
      if (!gtk_window_parse_geometry (GTK_WINDOW (window), geometry))
        g_printerr (_("Invalid geometry string \"%s\"\n"), geometry);
```

I.e., if I change the `geometry` string to something set in pixels, it works fine.
Need to understand if this behavior is intended and what is the best way to transform columns/rows into pixels.

**Comment by f2404** [comment]
@ochosi 
Do you guys have any idea about how to fix this? These geometry issues are really annoying.

**Comment by ochosi** [comment]
Basically gtk_window_parse_geometry calls gtk_window_set_default_size (which takes width/height in pixels), so you need to compute that based on the character size from VTE.

An implementation of that is to be found in gnome-terminal, more specifically here: https://github.com/GNOME/gnome-terminal/blob/master/src/terminal-window.c#L3567
This takes care of the calculations and terminal_window_parse_geometry (a few lines above) applies it.

**Comment by f2404** [comment]
Yep, I was able to resolve this particular issue by calculating the initial geometry in pixels.
But, the other issues with changing the size on adding tabs or moving the scrollbar still persisted so I discarded that work. Looks like something more should be done.
But thanks for the link anyway!

**Comment by f2404** [comment]
Closed by https://github.com/f2404/xfce4-terminal3/commit/3120466184c50905cea5aa8b098d651604837a21
