### ISSUE TITLE
Please merge your work to git.xfce.org

### ISSUE THREAD

**Issue by ochosi** [f2404/xfce4-terminal3#6]
Hey!
While nobody was working actively on xfce4-terminal in the recent past, I've merged some initial gtk3/vte3 to master on git.xfce.org.

If you're interested to get your code upstream that would be much appreciated! Would be great if you could start by attaching your work so far (i.e. what is not in our master branch already) as patches to Bugzilla or create a fork here on github so I have an easier time reviewing and merging your work.

Please note that we're trying to support Gtk<3.20 as well in our next release and I noticed that your port doesn't compile with Gtk3.18 - would be great if you could look into that!

Cheers
Simon

**Comment by f2404** [comment]
Hey @ochosi 

I was absolutely going to offer my efforts to upstream; the thing that's bothering me most atm is the geometry issue - the terminal window is too small on start, and it keeps resizing on adding/removing tabs, etc. On the other hand, I'm lost there, and probably need help from the community.

For the gtk 3.18 compilation - I only have machines with gtk 3.20 installed. I will try to use Travis CI to test 3.18 build (though I've never used it before). Would appreciate any help from your side, too.
UP: No, it seems Travis does not allow `xfce4-dev-tools` which is required for build. I will try to build it under Debian 8 in VirtualBox.

Thanks!

**Comment by f2404** [comment]
The Gtk<3.20 build issue has been resolved in this commit: https://github.com/f2404/xfce4-terminal3/commit/505be89fdff091c0dadf967b18c4410071f07f09
Now gtk+-3.0>=3.14 and vte-2.91>=0.38 are required; build verified on Debian 8.

**Comment by ochosi** [comment]
I tested your port and it generally works well - nice work!

Thanks for the pull-request, is that everything your branch was ahead on?

**Comment by f2404** [comment]
Yes, I pushed everything I got so far.
Btw, I saw an issue in your code but the issues are disabled in the repo. What is the reason for that?

**Comment by ochosi** [comment]
Awesome - thanks a lot!

Issues are disabled because bugs.xfce.org is the correct place to track bugs in Xfce ;)
Plus github was never intended for development, everything should be on git.xfce.org, but unfortunately currently our gitolite instance is a bit broken.

**Comment by f2404** [comment]
You are welcome :) hope my efforts will be useful since I'd really like to get rid of that bracketed input bug! :)

**Comment by ochosi** [comment]
Yes, they are much appreciated. If you discover more issues feel free to get in touch, you can also find us on chat.freenode.org in #xfce-dev

**Comment by ochosi** [comment]
Another question, did the scrollbar ever work in your port?

**Comment by f2404** [comment]
Yes, it's working in my repo version.

**Comment by f2404** [comment]
Ah, sorry, no, it's not working now. I don't know if it ever worked.

**Comment by f2404** [comment]
@ochosi, [This](https://github.com/f2404/xfce4-terminal3/commit/826dd9d27d71fa0178c1818ff048e87bff9d68bd) commit made it work. However, the scrollbar mark is not moving (though the contents gets scrolled) - I will look further into it.
UP: The scrollbar is fixed now.
